### ISSUE TITLE
Plugin crashes.

### ISSUE THREAD

**Issue by wybrandvdmeer** [innobead/pygradle#11] opened 2017-06-26 07:55 UTC
Gradle version:

$ gradle --version

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Linux 4.4.0-53-generic amd64

Stacktrace:
Caused by: java.lang.NoSuchMethodError: org.gradle.process.ExecSpec.setWorkingDir(Ljava/io/File;)V
        at com.innobead.gradle.task.PythonTestTask$action$2.execute(PythonTestTask.kt:64)
        at com.innobead.gradle.task.PythonTestTask$action$2.execute(PythonTestTask.kt:12)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:175)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1036)
        at com.innobead.gradle.task.PythonTestTask.action(PythonTestTask.kt:62)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:692)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:675)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 70 more

**Comment by innobead** [comment] 2017-06-26 18:18
The issue is resolved in 1.0.17. Thanks!

**Closed as completed by innobead** 2017-06-26 18:18 UTC
